<div class="bs-docs-section">
    <div class="well">
        <?php

        $form->setAttribute('action', $this->url('admin/article', ['action' => 'add']));
        $form->prepare();

        echo $this->form()->openTag($form);
        echo '<fieldset><legend>Adding article</legend>';
        foreach ($form as $element) {
            echo '<div class="form-group">';
            $attributes = $element->getAttributes();

            $label = '';

            if ($element->getLabel()) {
                $element->setLabelAttributes(['class' => 'col-lg-2 control-label']);
                $label = $element->getLabel();

                if (isset($attributes['required'])) {
                    $label .= ' *';
                }

                $label = '<label class="col-lg-2 control-label">' . $label . '</label>';
            }

            $type = isset($attributes['type']) ? $attributes['type'] : '';
            $formElement = '';


            switch ($type) {
                case 'text':
                    $formElement = $this->formInput($element);
                    break;
                case 'textarea':
                    $formElement = $this->formtextArea($element);
                    break;
                case 'select':
                    $formElement = $this    ->formSelect($element);
                    break;
                case 'checkbox':
                    $formElement = $this->formCheckBox($element);
                    break;
                default:
                    $formElement = $this->formRow($element);
                    $label = '';
                    break;
            }

            echo $label;
            echo '<div class="col-lg-10">' . $formElement . '</div>';
            echo '</div>';
        }

        echo '</fieldset>';
        $this->form()->closeTag();
        ?>
    </div>
</div>

<script src="/js/ckeditor/ckeditor.js"></script>