<div class="bs-docs-section">
    <div class="well">
        <?php
        $form->setAttribute('action', $this->url('admin/category', ['action'=> 'edit', 'id'=>$id]));
        $form->prepare();

        echo $this->form()->openTag($form);
        echo '<fieldset><legend>Edit category</legend>';
        foreach ($form as $element) {
            echo '<div class="form-group">';
            $attributes = $element->getAttributes();

            if ($element->getLabel()) {
                $element->setLabelAttributes(['class' => 'col-lg-2 control-label']);
                if (isset($attributes['required'])) {
                    $element->setLabel($element->getLabel() . ' *');
                }
            }

            if($element->getLabel()){
                echo $this->formLabel($element);
            }

            echo '<div class="col-lg-10">';
            if (isset($attributes['type']) && $attributes['type'] == 'text') {
                echo $this->formInput($element);
            } elseif (isset($attributes['type']) && $attributes['type'] == 'textarea') {
                echo $this->formTextArea($element);
            } elseif (isset($attributes['type']) && $attributes['type'] == 'file') {
                echo $this->formFile($element);
            } else {
                echo $this->formRow($element);
            }
            echo '</div>';


            echo '</div>';
        }

        echo '</fieldset>';
        $this->form()->closeTag();
        ?>
    </div>
</div>